// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 列表基礎需求 request
type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

// 狀態回報
type StatusReply struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Unix                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=unix,proto3" json:"unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *StatusReply) GetUnix() *timestamp.Timestamp {
	if m != nil {
		return m.Unix
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "base.ListRequest")
	proto.RegisterType((*StatusReply)(nil), "base.StatusReply")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4f, 0xc6, 0x20,
	0x10, 0x86, 0x53, 0xbf, 0x6a, 0x22, 0x5d, 0x0c, 0x53, 0xf3, 0x2d, 0x36, 0x5d, 0xac, 0x0b, 0x24,
	0x1a, 0xff, 0x80, 0xb3, 0x13, 0x3a, 0xb9, 0x01, 0x5e, 0x11, 0x2d, 0x1e, 0xca, 0x91, 0x54, 0x7f,
	0xbd, 0x81, 0xa6, 0xba, 0x3d, 0xf7, 0xe6, 0xbd, 0xe4, 0x79, 0x19, 0x33, 0x3a, 0x81, 0x88, 0x5f,
	0x48, 0xc8, 0xdb, 0xc2, 0xc7, 0x4b, 0x87, 0xe8, 0x16, 0x90, 0x35, 0x33, 0x79, 0x96, 0xe4, 0x03,
	0x24, 0xd2, 0x21, 0x6e, 0xb5, 0xf1, 0x8e, 0x75, 0x0f, 0x3e, 0x91, 0x82, 0xcf, 0x0c, 0x89, 0x38,
	0x67, 0x6d, 0xd4, 0x0e, 0xfa, 0x66, 0x68, 0xa6, 0x53, 0x55, 0xb9, 0x64, 0xc9, 0xff, 0x40, 0x7f,
	0xb2, 0x65, 0x85, 0x47, 0xcb, 0xba, 0x47, 0xd2, 0x94, 0x93, 0x82, 0xb8, 0x7c, 0x97, 0x8a, 0xc5,
	0x97, 0xbf, 0xb7, 0xc2, 0xfc, 0x82, 0x1d, 0x42, 0x72, 0xf5, 0xeb, 0x5c, 0x15, 0xe4, 0x82, 0xb5,
	0xf9, 0xc3, 0xaf, 0xfd, 0x61, 0x68, 0xa6, 0xee, 0xe6, 0x28, 0x36, 0x37, 0xb1, 0xbb, 0x89, 0xa7,
	0xdd, 0x4d, 0xd5, 0xde, 0xfd, 0xf5, 0xf3, 0x95, 0xf3, 0xf4, 0x9a, 0x8d, 0xb0, 0x18, 0x64, 0xd0,
	0xeb, 0xdb, 0xfb, 0x6c, 0xa5, 0x45, 0x8b, 0x8b, 0xfe, 0x5f, 0x54, 0x76, 0x9a, 0xb3, 0x7a, 0xde,
	0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x18, 0xcd, 0x84, 0x8f, 0x02, 0x01, 0x00, 0x00,
}
